//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3DS_link_trade_bot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IpAddress {
            get {
                return ((string)(this["IpAddress"]));
            }
            set {
                this["IpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string discordtoken {
            get {
                return ((string)(this["discordtoken"]));
            }
            set {
                this["discordtoken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string botfc {
            get {
                return ((string)(this["botfc"]));
            }
            set {
                this["botfc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Pokemonwanted {
            get {
                return ((int)(this["Pokemonwanted"]));
            }
            set {
                this["Pokemonwanted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public global::System.Collections.Generic.List<System.UInt64> botchannels {
            get {
                return ((global::System.Collections.Generic.List<System.UInt64>)(this["botchannels"]));
            }
            set {
                this["botchannels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public global::System.Collections.Generic.List<System.UInt64> wtchannels {
            get {
                return ((global::System.Collections.Generic.List<System.UInt64>)(this["wtchannels"]));
            }
            set {
                this["wtchannels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gtsbool {
            get {
                return ((bool)(this["gtsbool"]));
            }
            set {
                this["gtsbool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool wtbool {
            get {
                return ((bool)(this["wtbool"]));
            }
            set {
                this["wtbool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pip")]
        public string botot {
            get {
                return ((string)(this["botot"]));
            }
            set {
                this["botot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42069")]
        public int bottid {
            get {
                return ((int)(this["bottid"]));
            }
            set {
                this["bottid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42069")]
        public int botsid {
            get {
                return ((int)(this["botsid"]));
            }
            set {
                this["botsid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ribbons {
            get {
                return ((bool)(this["Ribbons"]));
            }
            set {
                this["Ribbons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool matchpokeball {
            get {
                return ((bool)(this["matchpokeball"]));
            }
            set {
                this["matchpokeball"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool userpokeball {
            get {
                return ((bool)(this["userpokeball"]));
            }
            set {
                this["userpokeball"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool memes {
            get {
                return ((bool)(this["memes"]));
            }
            set {
                this["memes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool trainerinfo {
            get {
                return ((bool)(this["trainerinfo"]));
            }
            set {
                this["trainerinfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool batchedit {
            get {
                return ((bool)(this["batchedit"]));
            }
            set {
                this["batchedit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English")]
        public global::PKHeX.Core.LanguageID botlang {
            get {
                return ((global::PKHeX.Core.LanguageID)(this["botlang"]));
            }
            set {
                this["botlang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"""""funkygamer26"", ""chloegarcia"", ""volcano.“do”"", ""33012888"", ""edou"", ""moon."", ""unknown.yt"", ""japan.kebuju"", ""はちゆきおし"", ""あああ"", ""あか"", ""adventrsnivy"", ""noxii"", """", "" "", ""doudou#6666"", ""doudou#9999"", ""zeraoratv=yt"", ""sun."", ""leonmaxi.tv"", ""rayky"", ""kewl"", ""not toxi"", ""serkan"", ""arceus"", ""flecheringyt"", ""quit the gts"", ""0""""")]
        public global::System.Collections.Generic.List<string> knowngtsbreakers {
            get {
                return ((global::System.Collections.Generic.List<string>)(this["knowngtsbreakers"]));
            }
            set {
                this["knowngtsbreakers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool sendstatusmessage {
            get {
                return ((bool)(this["sendstatusmessage"]));
            }
            set {
                this["sendstatusmessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ulong pingroleid {
            get {
                return ((ulong)(this["pingroleid"]));
            }
            set {
                this["pingroleid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gen 7 Link Trade Bot is Online")]
        public string pingmessage {
            get {
                return ((string)(this["pingmessage"]));
            }
            set {
                this["pingmessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ulong WTPChannels {
            get {
                return ((ulong)(this["WTPChannels"]));
            }
            set {
                this["WTPChannels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WhoThat {
            get {
                return ((bool)(this["WhoThat"]));
            }
            set {
                this["WhoThat"] = value;
            }
        }
    }
}
